package com.codeit.sb13.monew.activity.outbox.domain;

public enum OutboxEventType {
    INTEREST_SUBSCRIBED,
    INTEREST_UNSUBSCRIBED,
    COMMENT_WRITTEN,
    COMMENT_LIKED,
    COMMENT_LIKE_CANCELED,
    ARTICLE_VIEWED,
    INTEREST_UPDATED,
    INTEREST_HARD_DELETED,
    COMMENT_UPDATED,
    COMMENT_SOFT_DELETED,
    COMMENT_HARD_DELETED,
    ARTICLE_SOFT_DELETED,
    ARTICLE_HARD_DELETED,
    USER_NICKNAME_UPDATED,
    USER_SOFT_DELETED,
    USER_HARD_DELETED,
    INTEREST_SUBSCRIBER_COUNT_CHANGED,
    COMMENT_LIKE_CHANGED,
    ARTICLE_VIEW_COUNT_CHANGED,
    ARTICLE_COMMENT_COUNT_CHANGED
}
